In [12]:
import numpy as np
import math
from scipy.spatial.transform import Rotation as R

/usr/lib/python3/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [18]:
camera_rotation_matrix.astype(np.float16)

array([[ 0., -1., -0.],
       [-0.,  0., -1.],
       [ 1.,  0., -0.]], dtype=float16)

In [3]:
translation_matrix = np.load("/home/hguda/colab_dress_ws/camera_transform_after_rotation.npy").astype(float)

In [19]:
trans = np.load("/home/hguda/colab_dress_ws/translation_matrix.npy").astype(float)

In [22]:
np.linalg.norm(trans[:3, 3])

1.0009426629545009

In [25]:
np.linalg.norm(point_3d)

1.4186042436141237

In [24]:
x, y, z  = 0.03, 0.13, 0.53
x=-0.057
y=0.242
z=0.975
point_3d = np.array([x, y, z, 1.0])  # Homogeneous coordinates
transformed_point = translation_matrix @ point_3d
transformed_point

array([ 0.59402779, -0.32595616,  1.51584948,  1.        ])

In [10]:
# x = 0.36725354194641113
# y = 0.01193310134112835
# z = -0.02403038926422596
after_trans = np.array([0.36725354194641113, 0.01193310134112835, -0.02403038926422596, 1.0])

In [36]:
new_trans = np.eye(4)
new_trans[:3, :3] = camera_rotation_matrix

new_trans = new_trans @ trans

In [37]:
new_trans[:3, 3] = trans[:3, 3] + np.array([0.367, 0.0119, -0.024])

In [40]:
np.linalg.norm(np.array([0.367, 0.0119, -0.024]))

0.3679763715240423

In [39]:
np.linalg.norm(new_trans @ point_3d)

1.1446111101179073

In [46]:
T_camera_rotation = np.eye(4)
camera_rotation_matrix = R.from_euler('xyz', [math.radians(135.0), math.radians(-90.0), math.radians(-45.0)]).as_matrix()
T_camera_rotation[:3, :3] = camera_rotation_matrix
T_camera_to_marker = np.load("/home/hguda/colab_dress_ws/translation_matrix.npy").astype(float)# @ T_camera_rotation

In [47]:
T_marker_to_base = np.eye(4)
T_marker_to_base[:3, 3] = np.array([0.367, 0.0119, -0.024])


In [49]:
T_marker_to_base @ T_camera_to_marker

array([[ 0.67483199,  0.29474378, -0.67655593,  0.9908538 ],
       [ 0.73709053, -0.31398463,  0.59842396, -0.45115397],
       [-0.03604642, -0.90251857, -0.42913973,  0.60708927],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [52]:
T_camera_to_marker - T_marker_to_base @ T_camera_to_marker

array([[ 0.    ,  0.    ,  0.    , -0.367 ],
       [ 0.    ,  0.    ,  0.    , -0.0119],
       [ 0.    ,  0.    ,  0.    ,  0.024 ],
       [ 0.    ,  0.    ,  0.    ,  0.    ]])

In [54]:
T_camera_to_marker

array([[ 0.67483199,  0.29474378, -0.67655593,  0.6238538 ],
       [ 0.73709053, -0.31398463,  0.59842396, -0.46305397],
       [-0.03604642, -0.90251857, -0.42913973,  0.63108927],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [53]:
T_camera_to_marker @ point_3d

array([-0.00292566,  0.00241095, -0.00367682,  1.        ])

In [48]:
P_base = T_marker_to_base @ T_camera_to_marker @ point_3d
P_base

array([ 0.36407434,  0.01431095, -0.02767682,  1.        ])