In [1]:
import numpy as np

In [31]:
arr = np.load("/home/hguda/repos/colab_dress_ros_ws/translation_matrix.npy")
cP = np.array([-0.22581208,  0.22597449,  0.83200002, 1.0])

In [5]:
arr @ tvec.T

array([2.01777541e-08, 1.71580192e-08, 2.27392298e-08, 1.00000000e+00])

In [8]:
arr

array([[-0.06808294, -0.91303384, -0.4021616 ,  0.42958277],
       [-0.5572419 ,  0.36916104, -0.7437752 ,  0.5452296 ],
       [ 0.8275543 ,  0.17346291, -0.53391427,  0.87038314],
       [ 0.        ,  0.        ,  0.        ,  1.        ]],
      dtype=float32)

In [6]:
F_T_E = np.array([[0.725, -0.689, -0.005,  0.376],  
                  [-0.689, -0.725, -0.015, -0.033],
                  [0.007,  0.015, -1.000,  0.487],
                  [0.000,  0.000,  0.000,  1.000]])

In [ ]:
T = np.array([[0.696, -0.718,  0.009,  0.365],
              [-0.718, -0.696, -0.028,  0.023],
              [0.026,  0.013, -1.000,  0.183],
              [0.000,  0.000,  0.000,  1.000]])

In [13]:
T_new = np.linalg.inv(T) @ arr

In [24]:
tvec4 = np.array([0.365, 0.023, 0.183, 1.0])

In [26]:
np.linalg.inv(T) @ tvec4.T

array([ 0.00482151,  0.00238186, -0.18284368,  1.        ])

In [ ]:
import numpy as np
from scipy.spatial.transform import Rotation as R

x, y, z = 0.367, 0.017, -0.027 - 0.00975
tvec4 = np.array([ 0.367, 0.017, -0.027, 1.0])
qx, qy, qz, qw = 1.000, -0.008, 0.005, 0.014

rot = R.from_quat([qx, qy, qz, qw]).as_matrix()
T = np.eye(4)
T[:3, :3] = rot
T[:3, 3] = [x, y, z]
print(T)

[[ 0.99982205 -0.0161354   0.00977321  0.367     ]
 [-0.01585548 -0.99948015 -0.028072    0.017     ]
 [ 0.01022109  0.02791205 -0.99955813 -0.027     ]
 [ 0.          0.          0.          1.        ]]


In [37]:
np.linalg.inv(T) @ tvec4.T

array([5.55111512e-17, 1.73472348e-18, 0.00000000e+00, 1.00000000e+00])

In [38]:
T @ arr @ cP.T

array([ 0.36699998,  0.01700002, -0.02699999,  1.        ])

In [ ]:
ros2 topic pub --once /dmp/arm_poses geometry_msgs/msg/PoseArray "{header: {frame_id: 'base'}, poses: [{position: {x: 0.424, y: -0.025, z: 0.286}, orientation: {w: 1.0}}, {position: {x: 0.424, y: -0.025, z: 0.186}, orientation: {w: 1.0}}, {position: {x: 0.424, y: -0.025, z: 0.086}, orientation: {w: 1.0}}]}"

In [ ]:
ros2 topic pub --once /dmp/arm_poses geometry_msgs/msg/PoseArray "{header: {frame_id: 'base'}, poses: [{position: {x: 0.375, y: -0.035, z: 0.276}, orientation: {w: 1.0}}, {position: {x: 0.474, y: -0.035, z: 0.276}, orientation: {w: 1.0}}, {position: {x: 0.574, y: -0.035, z: 0.276}, orientation: {w: 1.0}}]}"